br-profile: created profile ui
VentionCapstone/Mobile pull request #1
Opened 2023-11-29 16:51 UTC by melievkh

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +interface CustomButtonProps extends TouchableOpacityProps {
Let's create a separate file for types. For example: `Button.types.ts`

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +  const getButtonStyle = (): ViewStyle => {
Let's move this helper functions to a separate file. If these are relevant to Button.tsx only, then we should create `Button.utils.tsx` file and place these functions there.

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +  paddingVertical: 10,
We can create a predefined padding values like xxs, xs, s, m, l, xl, xxl => 5, 10, 15

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +const styles = StyleSheet.create({
Let's move these styles into a separate file. For example: `Button.styles.js`.

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +    color: '#ddd',
We should have a predefined color template values and we should use them

2023-11-30 16:11 UTC, hgoziev commented on src/components/Button/Button.tsx
> +    fontSize: 18,
The same with FontSize as well. We should have a set of font size values defined in one place and used in different places with their names.

2023-11-30 16:11 UTC, hgoziev commented on src/components/Inputs/Input.tsx
> +      {label && <Text style={styles.label}>{label}</Text>}
Do you have designs ready ? If you have it, can you share it to me ?

2023-11-30 16:11 UTC, hgoziev commented on src/components/Inputs/Input.tsx
> +        {icon && <MaterialIcons name={icon} size={24} style={styles.icon} />}
Icons could be on both sides. It's better to name it leftIcon and rightIcon.

2023-11-30 16:11 UTC, hgoziev commented on src/components/ProfileHeader/ProfileHeader.tsx
> +  const navigation = useNavigation<NavigationProp<any>>();
Let's not use `any` as type if possible.

2023-11-30 16:11 UTC, hgoziev commented on src/components/ProfileHeader/ProfileHeader.tsx
> +            onPress={() => navigation.navigate('redirectToCreate')}
All route names must be a constant value. For example: `routes.SIGNUP`

2023-11-30 16:11 UTC, hgoziev commented on src/components/ProfileHeader/ProfileHeader.tsx
> +                    uri: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYR2tzlAo8Mr4r_1MNOOVAsW-NXHnGmCuQwGTfda_x9RBu6YWP6X1ohBGSVtIHo4rzKjw&usqp=CAU',
This uri value should be in a constant value even it is  a mock data.

2023-11-30 16:11 UTC, hgoziev commented on src/navigation/stacks/ProfileStacks/CreateProfileStack.tsx
> +  const [fullname, setFullname] = useState('');
It's better to have a single useState object value to store all these information

2023-11-30 16:11 UTC, hgoziev commented on src/navigation/stacks/ProfileStacks/CreateProfileStack.tsx
> +          style={{ gap: 10 }}
Let's move to a separate styling file.

2023-11-30 16:11 UTC, hgoziev commented on src/navigation/stacks/ProfileStacks/CreateProfileStack.tsx
> +            <Text style={{ fontSize: 24, fontWeight: 'bold' }}>Profile</Text>
All Styles should be in a separate file (no matter how small ) and  used in actual component file.

2023-11-30 16:11 UTC, hgoziev commented on src/screens/ProfileScreen/ProfileScreen.tsx
> +        renderItem={({ item }) => (
`renderItem` and `ListFooterComponent` should be a separate function or component and should be used like `ListHeaderComponent`

2023-11-30 16:11 UTC, hgoziev commented on src/theme/index.tsx
> +export const useTheme = () => React.useContext(ThemeContext);
`useTheme` custom hook should handle an error.  

`const context = useContext(ThemeContext)`
`if(!context) throw error ... `
`return context`

2023-12-01 15:10 UTC, melievkh commented on src/components/Inputs/Input.tsx
> +      {label && <Text style={styles.label}>{label}</Text>}
you mean figma design or the design that I've created?

2023-12-09 16:24 UTC, javokhirm requested changes

2023-12-09 16:24 UTC, javokhirm commented on src/theme/index.tsx
no need to use context, include theme on redux-toolkit

2023-12-09 16:24 UTC, javokhirm commented on src/styles/containers.ts
> +export const FONT_SIZES = {
seems weird, why do you need FONT_SIZES as constant? better create a separate file as typography.ts and include common text styles

2023-12-09 16:24 UTC, javokhirm commented on src/types/index.ts
create dedicated files for each type, and use index.ts files as exporter files as you have done on many folders

2023-12-09 16:24 UTC, javokhirm commented on src/api/store/store.ts
`store` folder should be located in `src` folder, not inside `api` folder

2023-12-09 16:24 UTC, javokhirm commented on src/api/types.ts
we have `types` folder to include all types

2023-12-11 09:29 UTC, javokhirm approved these changes

2023-12-11 09:33 UTC, merged