Feature/18 auth
VentionCapstone/Mobile pull request #3
Opened 2023-12-15 05:54 UTC by VladimirNee

add:
redux slice and thunk for auth logic
screens for auth logic + placeholder for email validation
additional types and styles

2023-12-15 10:39 UTC, javokhirm requested changes

2023-12-15 10:39 UTC, javokhirm commented on src/components/ProfileHeader/ProfileHeader.tsx
>                  console.log('redirect to signin!');
remove console logs

2023-12-15 10:39 UTC, javokhirm commented on package.json
> +    "react-native-web": "~0.19.6",
why do you need `react-native-web`?

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signin/Signin.tsx
> +  const [formInteracted, setFormInteracted] = useState<boolean>(false);
you don't need `formInteracted` state

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signin/Signin.tsx
> +          <Text
style `Sign Up` text, it should be diplayed as it's a link

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signup/Signup.tsx
> +        error={formInteracted && formIsValid ? authError : null}
authError message is enough here, but keep in mind you should pass an error prop as string

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signin/Signin.tsx
> +          placeholder="Enter your password"
inputs have the same color for placeholder and text, let's make them different

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signup/Signup.tsx
> +  const authError = useSelector(getAuthError);
clear auth error when the page is opened and after the form submission

2023-12-15 10:39 UTC, javokhirm commented on src/store/slices/authSlice.ts
> +  tokens: null,
don't store tokens on reducer, better use `expo-secure-store`

2023-12-15 10:39 UTC, javokhirm commented on src/store/slices/authSlice.ts
> +      AsyncStorage.setItem('tokens', JSON.stringify(action.payload.tokens));
use a secure store to save sensitive info (tokens)

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signup/Signup.tsx
> +  const isPasswordMatch = credentials.password === credentials.confirm_password;
let's check this on `validateForm` function

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signin/Signin.tsx
> +        error={formInteracted && formIsValid ? authError : null}
authError message is enough

2023-12-15 10:39 UTC, javokhirm commented on src/screens/auth/Signup/Signup.tsx
> +      navigation.navigate('VerifyEmail');
navigate only if server returns success

2023-12-15 15:01 UTC, VladimirNee commented on package.json
> +    "react-native-web": "~0.19.6",
removed

2023-12-15 15:03 UTC, VladimirNee commented on src/screens/auth/Signin/Signin.tsx
> +  const [formInteracted, setFormInteracted] = useState<boolean>(false);
removed

2023-12-15 17:53 UTC, VladimirNee commented
resolved according to comments, but excluding styling of inputs. This needs to be discussed with Khushnud Meliev

2023-12-16 10:26 UTC, javokhirm approved these changes

2023-12-16 10:26 UTC, merged